[package]
name = "subseq_scheduling"
version = "0.1.0"
edition = "2021"
authors = ["Teague Lasser"]

[dependencies]
anyhow = "1.0.79"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
uuid = { version = "1.8.0", features = ["serde"] }
